FROM node:16-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG NEXTAUTH_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG FACEBOOK_CLIENT_ID
ARG FACEBOOK_CLIENT_SECRET
ARG DATABASE_URL
ARG OPENAI_API_KEY
ARG NEXT_PUBLIC_URL
ARG MIDTRANS_SERVER_KEY
ARG MIDTRANS_SERVER_KEY_HASHED
ARG MIDTRANS_SERVER_URL
ARG MIDTRANS_COREAPI_URL

ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
ENV FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
ENV DATABASE_URL=${DATABASE_URL}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
ENV MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
ENV MIDTRANS_SERVER_KEY_HASHED=${MIDTRANS_SERVER_KEY_HASHED}
ENV MIDTRANS_SERVER_URL=${MIDTRANS_SERVER_URL}
ENV MIDTRANS_COREAPI_URL=${MIDTRANS_COREAPI_URL}
RUN npx prisma generate
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
