name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Load .env.example file
        run: |
          if [ -f .env.example ]; then
            export $(cat .env.example | grep -v '#' | awk '/=/ {print $1}')
          fi

      - name: Export secrets as environment variables
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}" >> $GITHUB_ENV
          echo "FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "MIDTRANS_SERVER_KEY=${{ secrets.MIDTRANS_SERVER_KEY }}" >> $GITHUB_ENV
          echo "MIDTRANS_SERVER_KEY_HASHED=${{ secrets.MIDTRANS_SERVER_KEY_HASHED }}" >> $GITHUB_ENV
          echo "MIDTRANS_SERVER_URL=${{ secrets.MIDTRANS_SERVER_URL }}" >> $GITHUB_ENV
          echo "MIDTRANS_COREAPI_URL=${{ secrets.MIDTRANS_COREAPI_URL }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXTAUTH_URL=http://localhost:3000 \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --build-arg FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }} \
            --build-arg FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg NEXT_PUBLIC_URL=http://localhost:3000 \
            --build-arg MIDTRANS_SERVER_KEY=${{ secrets.MIDTRANS_SERVER_KEY }} \
            --build-arg MIDTRANS_SERVER_KEY_HASHED=${{ secrets.MIDTRANS_SERVER_KEY_HASHED }} \
            --build-arg MIDTRANS_SERVER_URL=${{ secrets.MIDTRANS_SERVER_URL }} \
            --build-arg MIDTRANS_COREAPI_URL=${{ secrets.MIDTRANS_COREAPI_URL }} \
            -t temansoal:latest .

      - name: Print Docker build logs
        if: failure()
        run: |
          CONTAINER_ID=$(docker ps -a -q --filter "ancestor=temansoal" --filter "status=exited" --no-trunc | head -n 1)
          docker logs $CONTAINER_ID

      - name: Tag Docker image
        if: success()
        run: docker tag temansoal:latest ${{ secrets.DOCKER_HUB_USERNAME }}/temansoal:latest

      - name: Push Docker image to DockerHub
        if: success()
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/temansoal:latest

      - name: Verify Docker image on DockerHub
        if: success()
        run: |
          sleep 10 # optional delay
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/temansoal:latest

      - name: Scan Docker image with Trivy
        if: success()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/temansoal:latest
          scan-type: image
          format: table
